services:
  web:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
